version: '3.8'

services:
  vm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl_vm
    ports:
      - "2222:22"  # SSH
    volumes:
      - .:/app  # Montar todo el proyecto
    networks:
      - etl_net

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - etl_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  etl_net:

volumes:
  postgres_data:
