version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_etl
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
      POSTGRES_DB: bronze_etl
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build: .  # construye la imagen usando Dockerfile
    container_name: etl_runner
    volumes:
      - .:/app  # sincroniza tu carpeta local con el contenedor
    working_dir: /app
    command: tail -f /dev/null  # mantiene el contenedor corriendo
    depends_on:
      - postgres

volumes:
  pgdata:
